---
    TRAIN_TEXT_COL: "comment_text_clean"
    TEST_TEXT_COL: "comment_text_clean"
    TRAIN_TARGET_COL: "target"
    TEST_TARGET_COL: "target"
    IDENTITY_COLS:
        - "male"
        - "female"
        - "homosexual_gay_or_lesbian"
        - "christian"
        - "jewish"
        - "muslim"
        - "black"
        - "white"
        - "christian"
        - "psychiatric_or_mental_illness"
    
    EMBEDDING_FILE: 'embeds/glove.840B.300d.txt'
    EMBEDDING_DIMS: 300
    MAX_VOCAB_SIZE: 300000
    MAX_LEN_SEQ: 300

    LSTM_UNITS: 128
    BATCH_SIZE: 128
    NUM_EPOCHS: 4
    LEARNING_RATE: 0.001

    CHECKPOINT_PATH: "NN_models/cp.ckpt"
    



